Update eigenvalue page
cs357/textbook pull request #10
Opened 2024-02-12 01:12 UTC by pascaladhikary

- reorganize in slide order
- include finding eval/evec example, code snippet
- replace cost summary with cost/convergence table

2024-02-13 03:08 UTC, jlevine18 requested changes
this is a good start- see my comments. i'd also take a bit of a closer look at some of the power iteration section that we currently have and give a little more to help students build intuition- we ask a lot of questions about errors/convergence/advantage of normalization, which the notes are somewhat lacking in. i'd also add a couple graphical examples as well to show eigenvals/eigenvecs as deformation directions, and convergence during the steps of power iteration. i'd also look into moving some stuff around in the power-iteration section and making that the whole text is cohesive and reads well. feel free to do things a little differently- the most important goals are that the material contains everything someone might need to do hw/a quiz and that it reads well

2024-02-13 03:08 UTC, jlevine18 commented on notes/eigen.md
maybe add a bit more explanation of runtime? especially with lu factorization

2024-02-13 03:09 UTC, jlevine18 commented
also it's probably worth doing one last check to make sure that everything from the slides/videos is in here

2024-02-16 20:24 UTC, jlevine18 approved these changes
looks good- thanks for your help

2024-02-23 19:41 UTC, merged

2024-02-23 19:42 UTC, devksingh4 reviewed
lgtm