first draft
cs357/textbook pull request #22
Opened 2024-02-28 05:35 UTC by kritic3

2024-03-02 21:04 UTC, jlevine18 requested changes
This looks very good so far- I would recommend also adding a section on finding good choices for the h parameter (sqrt of machine eps is often recommended, and some info is in Mariana's slides) as well as a couple graphical examples. Also, you might want to add a little more information on error bounds so that students have a bit more intuition on what's creating them. TYSM for everything so far.

2024-03-03 22:16 UTC, kritic3 commented on notes/finite-difference.md
> +For a given smooth function \\(f(x)\\), we want to calculate the derivative \\(f'(x)\\) at a given value of \\(x\\).
I think knowing the definition of a smooth function is part of the prerequisite knowledge for this class

2024-03-03 22:28 UTC, kritic3 commented on notes/finite-difference.md
> +For a differentiable function \\(f(x):\mathbb{R} \rightarrow \mathbb{R}\\), the derivative is defined as
I define that at the end. I thought defining a single variable was easier to understand before bringing up multivariable approximation. Should I mention it above too?

2024-03-15 22:24 UTC, jlevine18 approved these changes
Looks great; thank you so much for doing this

2024-03-19 00:22 UTC, merged